import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const nunito = localFont({
  src: [
    {
      path: "./fonts/Nunito-Light.ttf", // Light weight
      weight: "300", 
      style: "normal",
    },
    {
      path: "./fonts/Nunito-Regular.ttf", // Regular weight
      weight: "400", 
      style: "normal",
    },
    {
      path: "./fonts/Nunito-Medium.ttf", // Medium weight
      weight: "500", 
      style: "normal",
    },
    {
      path: "./fonts/Nunito-SemiBold.ttf", // Semi-Bold weight
      weight: "600", 
      style: "normal",
    },
    {
      path: "./fonts/Nunito-Bold.ttf", // Bold weight
      weight: "700", 
      style: "normal",
    },
    {
      path: "./fonts/Nunito-ExtraBold.ttf", // Extra-Bold weight
      weight: "800", 
      style: "normal",
    },
  ],
  variable: "--font-nunito", // Variable name for CSS custom property
});





export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <header>

      </header>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  ${nunito.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
