import type { Metadata } from "next";
import { Nunito } from "next/font/google"; 
import "./globals.css";

// Configure the Nunito font
const nunito = Nunito({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900", "1000"],
  style: ["normal", "italic"],
  variable: "--font-nunito", 
});

export const metadata: Metadata = {
  title: "Hemas-myFOODIE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.className} bg-white`}> {/* Apply the font to the body */}
        <header>
          {/* Your header content */}
        </header>
        {children}
      </body>
    </html>
  );
}